platform: linux

image_resource:
  type: docker-image
  source: {repository: limaofeng/gradle-alpine}

inputs:
- name: demo-actuator-test

outputs:
  - name: demo-actuator-test2

run:
  path: ./demo-actuator-test/ci/test.sh